server:
  port: 8083

file:
  upload:
    dir: E:/Project/JavaProject/flagship-mall/src/main/resources/static/upload/

spring:
  datasource:
    name: flagship_mall_datasource
    url: jdbc:mysql://localhost:3306/flagship_mall?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password:
  http:
    encoding:
      force: true
      charset: UTF-8
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  mapper-locations: classpath:mappers/*.xml
