server:
  port: 8083

spring:
  datasource:
    name: flagship_mall_datasource
    url: jdbc:mysql://localhost:3306/flagship_mall?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mappers/*.xml
